name: Run Pipeline

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: [self-hosted, home]
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm worker
